export const RESET_STORE = 'RESET_STORE';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const INCREASE_STREAK = 'INCREASE_STREAK';
export const RESET_STREAK = 'RESET_STREAK';
export const RESET_QUESTION = 'RESET_QUESTION';
export const SET_CORRECT_NOTE = 'SET_CORRECT_NOTE';
export const SET_CORRECT_REG = 'SET_CORRECT_REG';
export const SET_CORRECT_ANSWER = 'SET_CORRECT_ANSWER';
export const SET_QUESTION = 'SET_QUESTION';
export const SET_TREBLE = 'SET_TREBLE';
export const SET_BASS = 'SET_BASS';
export const TOGGLE_CLEF = 'TOGGLE_CLEF';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_CLEF = 'SET_CLEF';
export const SET_CLEF_SETTING = 'SET_CLEF_SETTING';
export const UPDATE_UNSWERED_NOTES = 'UPDATE_UNSWERED_NOTES';
export const UPDATE_UNSWERED_REGS = 'UPDATE_UNSWERED_REGS';
export const SET_WRONG_KEY = 'SET_WRONG_KEY';


