export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const INCREASE_STREAK = 'INCREASE_STREAK';
export const RESET_STREAK = 'RESET_STREAK';
export const SET_CORRECT_ANSWER = 'SET_CORRECT_ANSWER';
export const SET_QUESTION = 'SET_QUESTION';